### ISSUE TITLE
Customizable runs directory

### ISSUE THREAD

**Issue by NegatioN** [neptune-ai/neptune-mlflow#27]
Love the option of good interop between Mlflow and Neptune :slightly_smiling_face:

One suggestion for improvement: Not all mlflow directories are called `mlruns`. It seems weird that the CLI `neptune mlflow ${SOMEPATH}` checks for `${SOMEPATH}/mlruns` instead of just `${SOMEPATH}`

**Comment by aniezurawski** [comment]
Thanks for your suggestion. Is it still true that MLFlow always stores its data in mlruns directory or was it changed in latest versions?

**Comment by NegatioN** [comment]
Well, this might either be me misconfiguring things, or something has changed I guess.
By setting `MLFLOW_TRACKING_URI` in env, you can force the (local version) output directory to be anywhere you want it seems.

Structure of the folders become like this:
```
my_mlflow_dir $ ls
1  2  3  4

my_mlflow_dir/1 $ ls
5c98075f42024d42889a1063f1188267  meta.yaml

my_mlflow_dir/1/5c98075f42024d42889a1063f1188267$ ls
artifacts  meta.yaml  metrics  params  tags
```

**Comment by aniezurawski** [comment]
According to mlflow docs you can actually use MLFLOW_TRACKING_URI variable to configure custom directory. So I'm considering this as a bug on our side. We will fix this as soon as possible. Thanks for your report. :)

**Comment by SiddhantSadangi** [comment]
The Neptune-mlflow exporter now accepts the `mlflow_tracking_uri` as a parameter: https://docs.neptune.ai/api/integrations/mlflow/
