### ISSUE TITLE
Link to Documentation is Broken in README.md

### ISSUE THREAD

**Issue by 907Resident** [neptune-ai/neptune-mlflow#38]
I tried to access the documentation from the `README.md` but unfortunately it does not work. 

Here is the [LINK](https://docs.neptune.ai/integrations/mlflow.html) and below you can see the result when you click the link:

![image](https://user-images.githubusercontent.com/12258706/234971680-e7e17f86-8557-4ad0-87c8-31ae31a466bb.png)

**Comment by SiddhantSadangi** [comment]
Hey @907Resident , thanks for letting us know, and apologies for this issue.

You can find the docs [here](https://docs.neptune.ai/integrations/mlflow/), and we will update the README shortly.
Do note that the MLflow integration is not supported in the latest version of Neptune's Python client. We are working on a new MLFlow exporter and will make it available shortly.

I am closing this issue for now, but please do not hesitate to reopen it in case you have issues using the integration or need help with anything else.

Have a great day ahead! :)

**Comment by 907Resident** [comment]
Thanks, @SiddhantSadangi. 

I am looking forward to the updated version that will work with `neptune-client>=0.16.8`. 

Also, a really big fan of Neptune, keep up the good work!

**Comment by SiddhantSadangi** [comment]
Hey @907Resident 👋 
I come bearing good news 🌟 

We have updated the `neptune-mlflow` to v1.0, which now supports `neptune>=1.0`. 🎉 
You can find the documentation [here](https://docs.neptune.ai/integrations/mlflow/).

I am also sharing the [upgrade guide to Neptune 1.0](https://docs.neptune.ai/setup/neptune-client_1-0_release_changes/) in case you are still using the old `neptune-client`.

Please let me know if you have any questions or feedback about this 🙏

**Comment by 907Resident** [comment]
Cool! Thanks for following up. This is great timing since I'm supposed to start using MLFlow for work.
